--- 
- hosts: 172.31.12.40
  become: yes
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present 
  - name: copy dynamic file into node server
    template:
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: restartapacheserver
  handlers:
  - name: restartapacheserver
    service:
     name: apache2
     state: restarted
