---
- hosts: all
  become: yes
  tasks:
  - name: Install webserver on redhat
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="Redhat"
  - name: Start webserver on redhat
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family=="Redhat"
  - name: Install apache2 on ubuntu
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: Start webserver on ubuntu
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian"