---
- hosts: all
  become: yes
  tasks:
  - name: Install webserver on redhat
    yum:
      name: httpd
      state: present
  - name: Start webserver on redhat
    service:
      name: httpd
      state: started