--- 
- hosts: apacheservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
     name: "{{myjavapackonubuntu}}"
     state: present
    when: ansible_os_family=="Debain"

  - name: Install java on redhat
    yum:
     name: "{{myjavapackonredhat}}"
     state: present 
    when: ansible_os_family=="Redhat"
 