--- 
- hosts: localhost
  become: yes
  tasks:
  - name: create ansible nodes
    ec2:
     key_name: ohio
     instance_type: t2.micro
     image: ami-00b167a8ba3157a0b
     wait: yes
     group: default
     count: 2
     vpc_subnet_id: subnet-063f3a565d2656be1
     assign_public_ip: yes
     region: us-east-2
     instance_tags:
        Name: AnsibleNodes