---
- hosts: all
  become: yes
  tasks:
  - name: Install tree software
    apt:
          name: tree
          state: present
  - name: Install wget software
    apt:
          name: wget
          state: present
  - name: Install apache2 
    apt:
          name: apache2
          state: present
  - name: Start webserver
    service:
          name: apache2
          state: started
  